### ISSUE TITLE
Handler not called 

### ISSUE THREAD

**Issue by Abhishek9634** [null09264/FRHyperLabel#17]
without handler(self, substring) it is not working

**Comment by RishiRanjanKesarwani** [comment]
I'm also facing the same issue...the handler block is not called.

**Comment by Abhishek9634** [comment]
Because in the same view if the other gesture is added then it will cancel the native methods of touch events so for this
example:
  UITapGestureRecognizer \* tap = [[UITapGestureRecognizer alloc] initWithTarget:self
                                                                           action:@selector(handleTapGestureForKeyBoard)];

```
tap.cancelsTouchesInView = NO; // add this also to avoid cancelling touch events
```

**Comment by RishiRanjanKesarwani** [comment]
this gesture recognizer should be added to the hyperlabel? But it will make the whole hyper label respond to the tap gesture instead of substrings

**Comment by Abhishek9634** [comment]
no no , if you have any kind of gesture added then only

**Comment by fischsux** [comment]
Thank you guys for the discussion, please try the latest release (1.0.3), bugs related to handler not called should be fixed
