### ISSUE TITLE
Emoji Problem

### ISSUE THREAD

**Issue by Offek** [null09264/FRHyperLabel#18]
First of all I would like to thank you for this awesome repository!
There is an issue when placing an emoji in the text, it really messes up the clickable frame.
It seems like the clickable frame moves (or expands) a line down starting from the line in which the emojis are in.

Try this text for example:
`@"Test Link1! Test Test TEST!  \ue410 \ue410 \ue410 \ue410 f  Test Test Link2 Test Link3 Test Test Test Link4 Test!"`

Link1 and Link2's clickable frames are not in place, while Link3 and Link4 are not even clickable.
What could be the issue?

Thanks!

**Comment by fischsux** [comment]
Hi, please try the latest release (1.0.3), should be fixed
