### ISSUE TITLE
NOT WORK in Swift 3

### ISSUE THREAD

**Issue by bartleby** [null09264/FRHyperLabel#23]
incorrectly calculated touch 

[Test.zip](https://github.com/null09264/FRHyperLabel/files/520151/Test.zip)

**Comment by jakubknejzlik** [comment]
I'm facing this issue too. Version 1.0.2 works ok.

**Comment by fischsux** [comment]
Hey guys, sorry for the long delay. The bug in the zip you provided is fixed in 1.0.4.
