### ISSUE TITLE
Unrecognized selector

### ISSUE THREAD

**Issue by davidtperk** [null09264/FRHyperLabel#5]
-[UILabel setLinksForSubstrings:withLinkHandler:]: unrecognized selector sent to instance

Have you ever gotten this? I'm trying to instantiate substrings within each cell of a tableview. So I have all of these methods within cellForRowAtIndexPath. So I'm using cell.commentLabel.setLinksForSubstrings([String], withLinkHandler: { (label, string) -> Void in. 

Can't understand why I'd be getting that exception.

**Comment by fischsux** [comment]
Guess it's due to the reuse of tableViewCell.

Try cleaning the selector dictionary first by calling `clearActionDictionary`, then set the link in `cellForRowAtIndexPath` method

**Comment by MattTW** [comment]
I'm getting this same issue in a reusable cell.   clearActionDictionary doesn't seem to fix it.
