### ISSUE TITLE
link with two words

### ISSUE THREAD

**Issue by Voley** [null09264/FRHyperLabel#6]
I'm trying to set a link for text @"one two" but i can click only on the first word. I think this is a bug.

```
NSString *substring = NSLocalizedString(@"one two", nil);
[self.noVisitsTextLabel setLinksForSubstrings:@[substring] withLinkHandler:^(FRHyperLabel *label,    NSString *substring) {
    NSLog(@"Clicked");
}];
```

**Comment by leojini** [comment]
Hi! Voley
I think not a bug.

If you want to click on the first word, try the next code.

NSString *substring = NSLocalizedString(@"one two", nil);
[self.noVisitsTextLabel setLinksForSubstrings:@"one" withLinkHandler:^(FRHyperLabel *label,    NSString *substring) {
    NSLog(@"Clicked");
}];
