### ISSUE TITLE
Alignment Justify

### ISSUE THREAD

**Issue by alinekborges** [null09264/FRHyperLabel#7]
I'm not sure if it's really a problem, but when I was using "justify aligmnent" in label, some links were not being correctly called. When I changed to normal Left Alignment, touch recognition was a lot better. I did just some basic tests, so it would be good if someone else found the same problem.

Thanks for great work with this lib :)

**Comment by fischsux** [comment]
Would you like to try 1.0.4? I think justify alignment has already been supported. Please let me know if it's still not working, I'll re-open the issue.

Thanks for supporting. :)
