### ISSUE TITLE
How to remove underline from links?

### ISSUE THREAD

**Issue by jonataspc** [null09264/FRHyperLabel#8]
Hi,

Is that possible to remove underline from the links?

Thanks!

**Comment by fischsux** [comment]
Sure, you can define the property `linkAttributeDefault` and `linkAttributeHighlight` yourself. The underline is added only if these two properties are not explicitly specified.

**Comment by jonataspc** [comment]
Thanks dude!
By the way, awesome job. Your library saved my day.

**Comment by fischsux** [comment]
Glad to help :D
