### ISSUE TITLE
Handler not called in iPad - iOS 9 

### ISSUE THREAD

**Issue by jonataspc** [null09264/FRHyperLabel#9]
Hello,

The following code works great on iPhone but not in iPad.

The handler is called only if I tap in some interval after the end of the text.
I am very begginer to Obj-C language, but it seems to be related to the "attributedTextRangeForPoint" function. 

```
    lblInfoContact.text = ""
    lblInfoContact.numberOfLines = 0;

    //Step 1: Define a normal attributed string for non-link texts
    let attributes = [NSForegroundColorAttributeName: UIColor.blackColor(),
        NSFontAttributeName: UIFont.systemFontOfSize(13.0)]

    lblInfoContact.attributedText = NSAttributedString(string: myString, attributes: attributes)

    //Step 2: Define a selection handler block
    let handler = {
        (hyperLabel: FRHyperLabel!, substring: String!) -> Void in

        if substring == "CHAT" {
            Utils.showChat(self)
        }

        if substring == "CallBack" {
            Utils.showCallBack(self)
        }

    }

    //Step 3: Add link substrings
    lblInfoContact.setLinksForSubstrings(["CHAT", "CallBack"], withLinkHandler: handler)
```

**Comment by fischsux** [comment]
Hi, thanks for the issue :) Yeah, there is some problems with the `attributedTextRangeForPoint` function but I haven't figured out how to address them. Some work around might exist, but they are not guaranteed to work every time. Refer to the wiki page here https://github.com/null09264/FRHyperLabel/wiki/Known-Issues

**Comment by jonataspc** [comment]
Ok, thanks for the reply.
